package com.jg.videonotebook.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table VIDEO_NOTES.
*/
public class VideoNoteDao extends AbstractDao<VideoNote, Long> {

    public static final String TABLENAME = "VIDEO_NOTES";

    /**
     * Properties of entity VideoNote.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Date = new Property(1, java.util.Date.class, "date", false, "DATE");
        public final static Property Comments = new Property(2, String.class, "comments", false, "COMMENTS");
        public final static Property VideoUri = new Property(3, String.class, "videoUri", false, "VIDEO_URI");
        public final static Property NotebookId = new Property(4, long.class, "notebookId", false, "NOTEBOOK_ID");
    };

    private DaoSession daoSession;

    private Query<VideoNote> notebook_EntriesQuery;

    public VideoNoteDao(DaoConfig config) {
        super(config);
    }
    
    public VideoNoteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'VIDEO_NOTES' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DATE' INTEGER," + // 1: date
                "'COMMENTS' TEXT," + // 2: comments
                "'VIDEO_URI' TEXT," + // 3: videoUri
                "'NOTEBOOK_ID' INTEGER NOT NULL );"); // 4: notebookId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VIDEO_NOTES'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, VideoNote entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(2, date.getTime());
        }
 
        String comments = entity.getComments();
        if (comments != null) {
            stmt.bindString(3, comments);
        }
 
        String videoUri = entity.getVideoUri();
        if (videoUri != null) {
            stmt.bindString(4, videoUri);
        }
        stmt.bindLong(5, entity.getNotebookId());
    }

    @Override
    protected void attachEntity(VideoNote entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public VideoNote readEntity(Cursor cursor, int offset) {
        VideoNote entity = new VideoNote( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // date
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // comments
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // videoUri
            cursor.getLong(offset + 4) // notebookId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, VideoNote entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setComments(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setVideoUri(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNotebookId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(VideoNote entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(VideoNote entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "entries" to-many relationship of Notebook. */
    public List<VideoNote> _queryNotebook_Entries(long notebookId) {
        synchronized (this) {
            if (notebook_EntriesQuery == null) {
                QueryBuilder<VideoNote> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.NotebookId.eq(null));
                queryBuilder.orderRaw("DATE ASC");
                notebook_EntriesQuery = queryBuilder.build();
            }
        }
        Query<VideoNote> query = notebook_EntriesQuery.forCurrentThread();
        query.setParameter(0, notebookId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getNotebookDao().getAllColumns());
            builder.append(" FROM VIDEO_NOTES T");
            builder.append(" LEFT JOIN NOTEBOOK T0 ON T.'NOTEBOOK_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected VideoNote loadCurrentDeep(Cursor cursor, boolean lock) {
        VideoNote entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Notebook notebook = loadCurrentOther(daoSession.getNotebookDao(), cursor, offset);
         if(notebook != null) {
            entity.setNotebook(notebook);
        }

        return entity;    
    }

    public VideoNote loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<VideoNote> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<VideoNote> list = new ArrayList<VideoNote>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<VideoNote> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<VideoNote> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
